version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_DATABASE=shipment-tracking-db
volumes:
  mongodb-data:
